<?php
define('GET_RANDOM_IMAGE_ID', 'GET_RANDOM_IMAGE_ID');
define('INCREASE_VIEW_NUMBER', 'INCREASE_VIEW_NUMBER');
define('GET_CURRENT_VIEW_COUNT', 'GET_CURRENT_VIEW_COUNT');
define('UPDATE_CURRENT_VIEW_COUNT', 'UPDATE_CURRENT_VIEW_COUNT');